#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$HOME/benchmarking_run/Benchmarking}"
VENV="${VENV:-$HOME/benchmarking_run/.venv}"
VOLUME_ROOT="${VOLUME_ROOT:-/media/volume/TrainingData/txn_jatin_archs4}"
SOURCE_DATA_DIR="${SOURCE_DATA_DIR:-$VOLUME_ROOT/train_txn_jatin_full}"
TXN_DATA_DIR="${TXN_DATA_DIR:-$VOLUME_ROOT/train_txn_jatin_full_tpm_v2}"
TXN_CHECKPOINT_DIR="${TXN_CHECKPOINT_DIR:-$VOLUME_ROOT/checkpoints_v2}"
TXN_MODEL_NAME="${TXN_MODEL_NAME:-Txn_Jatin}"
TXN_RUN_ID="${TXN_RUN_ID:-Txn_Jatin_v2_full}"
TXN_EPOCHS="${TXN_EPOCHS:-10}"
NPROC_PER_NODE="${NPROC_PER_NODE:-1}"

cd "$PROJECT_ROOT"
source "$VENV/bin/activate"

export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM=false
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-$(nproc)}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-$(nproc)}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-$(nproc)}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-$(nproc)}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_PROJECT="${WANDB_PROJECT:-txn-jatin}"
export WANDB_NAME="${WANDB_NAME:-$TXN_MODEL_NAME-v2-full-archs4}"

echo "=== Txn_Jatin v2 full-data pipeline ==="
date
hostname
nvidia-smi
df -h "$PROJECT_ROOT" "$VOLUME_ROOT"

if [[ ! -f "$SOURCE_DATA_DIR/PREPARED_FULL_DATA.ok" ]]; then
  echo "=== Prepare full one-to-one ARCHS4 count shards ==="
  python scripts/txn_jatin_prepare_archs4_full.py \
    --project-root "$PROJECT_ROOT" \
    --output-dir "$SOURCE_DATA_DIR" \
    --download \
    --sequential-download
fi

echo "=== Build TPM harmonization and ESM2 gene prior ==="
python scripts/txn_jatin_build_harmonization.py \
  --project-root "$PROJECT_ROOT" \
  --source-dir "$SOURCE_DATA_DIR" \
  --output-dir "$TXN_DATA_DIR" \
  --resource-dir "$VOLUME_ROOT/resources/gencode" \
  --esm-features "$VOLUME_ROOT/priors/esm2_feature_concat.pt" \
  --hidden-dim "${BRIDGE_HIDDEN_DIM:-512}"

echo "=== Train $TXN_MODEL_NAME ==="
cd "$PROJECT_ROOT/RNA Walter"
export TXN_MODEL_NAME TXN_RUN_ID TXN_DATA_DIR TXN_CHECKPOINT_DIR
export BRIDGE_TARGET_EPOCHS="$TXN_EPOCHS"
export BRIDGE_DATA_MODE="${BRIDGE_DATA_MODE:-streaming}"
export BRIDGE_NORMALIZATION="${BRIDGE_NORMALIZATION:-counts_to_log1p_tpm}"
export BRIDGE_GENE_PRIOR_PATH="${BRIDGE_GENE_PRIOR_PATH:-$TXN_DATA_DIR/esm2_prior_${BRIDGE_HIDDEN_DIM:-512}d.npz}"
export BRIDGE_GENE_PRIOR_INIT="${BRIDGE_GENE_PRIOR_INIT:-1}"
export BRIDGE_GENE_PRIOR_WEIGHT="${BRIDGE_GENE_PRIOR_WEIGHT:-0.02}"
export BRIDGE_CONTEXT_PRIOR_WEIGHT="${BRIDGE_CONTEXT_PRIOR_WEIGHT:-0.03}"
export BRIDGE_SAMPLE_CONTRASTIVE_WEIGHT="${BRIDGE_SAMPLE_CONTRASTIVE_WEIGHT:-0.01}"
export BRIDGE_CONTRASTIVE_TEMPERATURE="${BRIDGE_CONTRASTIVE_TEMPERATURE:-0.1}"
export BRIDGE_ACCUMULATE_CONTEXT_EMBEDDINGS="${BRIDGE_ACCUMULATE_CONTEXT_EMBEDDINGS:-1}"
export BRIDGE_BENCHMARK_CONTEXT_WEIGHT="${BRIDGE_BENCHMARK_CONTEXT_WEIGHT:-0.0}"
export BRIDGE_BATCH_SIZE="${BRIDGE_BATCH_SIZE:-9}"
export BRIDGE_NUM_WORKERS="${BRIDGE_NUM_WORKERS:-8}"
export BRIDGE_PREFETCH_FACTOR="${BRIDGE_PREFETCH_FACTOR:-4}"
export BRIDGE_PERSISTENT_WORKERS="${BRIDGE_PERSISTENT_WORKERS:-1}"
export BRIDGE_STREAM_CACHE_SIZE="${BRIDGE_STREAM_CACHE_SIZE:-4}"
export BRIDGE_STREAM_DDP_FILE_SPLIT="${BRIDGE_STREAM_DDP_FILE_SPLIT:-0}"
export BRIDGE_TRAIN_SUBSET="${BRIDGE_TRAIN_SUBSET:-none}"
export BRIDGE_VAL_SUBSET="${BRIDGE_VAL_SUBSET:-20000}"
export BRIDGE_BALANCED_SAMPLING="${BRIDGE_BALANCED_SAMPLING:-0}"
export BRIDGE_BALANCED_SHARDS_ONLY="${BRIDGE_BALANCED_SHARDS_ONLY:-0}"
export BRIDGE_MAX_BALANCED_SHARDS="${BRIDGE_MAX_BALANCED_SHARDS:-none}"
export BRIDGE_USE_AMP="${BRIDGE_USE_AMP:-1}"
export BRIDGE_AMP_DTYPE="${BRIDGE_AMP_DTYPE:-bf16}"
export BRIDGE_LR="${BRIDGE_LR:-0.0001}"
export BRIDGE_WEIGHT_DECAY="${BRIDGE_WEIGHT_DECAY:-0.01}"
export BRIDGE_WARMUP_RATIO="${BRIDGE_WARMUP_RATIO:-0.02}"
export BRIDGE_MIN_LR_RATIO="${BRIDGE_MIN_LR_RATIO:-0.05}"
export BRIDGE_GRAD_CLIP_NORM="${BRIDGE_GRAD_CLIP_NORM:-1.0}"
export BRIDGE_EARLY_STOPPING="${BRIDGE_EARLY_STOPPING:-1}"
export BRIDGE_PATIENCE="${BRIDGE_PATIENCE:-3}"
export BRIDGE_TIMING_PROFILE="${BRIDGE_TIMING_PROFILE:-1}"
export BRIDGE_TIMING_CUDA_EVENTS="${BRIDGE_TIMING_CUDA_EVENTS:-0}"
export BRIDGE_PROGRESS_LOG_INTERVAL_SEC="${BRIDGE_PROGRESS_LOG_INTERVAL_SEC:-120}"
export BRIDGE_CHECKPOINT_INTERVAL_BATCHES="${BRIDGE_CHECKPOINT_INTERVAL_BATCHES:-2000}"

python -m torch.distributed.run \
  --nproc_per_node="$NPROC_PER_NODE" \
  flash_osdr_model/train_flash.py

echo "=== Benchmark $TXN_MODEL_NAME ==="
cd "$PROJECT_ROOT"
export MYTHOS_CLEAN_OUTPUTS=1
export BRIDGE_MODEL_NAME="$TXN_MODEL_NAME"
export BRIDGE_RUN="$TXN_RUN_ID"
export TXN_JATIN_CKPT="$TXN_CHECKPOINT_DIR/$TXN_RUN_ID/best_model.pt"
export BRIDGE_GENE_EMBED_MODE="${BRIDGE_GENE_EMBED_MODE:-checkpoint}"
export BRIDGE_INCLUDE_CONTEXTUAL_VARIANT="${BRIDGE_INCLUDE_CONTEXTUAL_VARIANT:-1}"
export MYTHOS_DEVICE=cuda
export MYTHOS_PROBE=torch
export MYTHOS_THREADS="${MYTHOS_THREADS:-$(nproc)}"
export MYTHOS_TCGA_MAX=0
export MYTHOS_OSDR_MAX_ACC=0
export MYTHOS_BENCH_MAX_GENES=200000
export MYTHOS_N_TERMS=100000
export MYTHOS_MAX_PAIRS=200000
export MYTHOS_BRIDGE_BATCH="${MYTHOS_BRIDGE_BATCH:-8}"
export MYTHOS_TORCH_PROBE_EPOCHS="${MYTHOS_TORCH_PROBE_EPOCHS:-80}"
export MYTHOS_OUTPUT_ROOT="${MYTHOS_OUTPUT_ROOT:-$VOLUME_ROOT/benchmark_outputs_txn_jatin_v2}"

python execute_txn_jatin_benchmark.py

echo "=== Done ==="
date
